### ISSUE TITLE
Discrepancias de Path.

### ISSUE THREAD

**Issue by worker-8** [aether7/react-tutorial#1]
En el punto que la app se reconstruye de forma modular 

> texto ref. para búsqueda Finally, our entire codebase should be this

 El documento dice que la path es `'./components/ExampleApp'` pero el instalador pone la carpeta components dentro de la carpeta static/js en ese caso la path debería ser `'./static/js/components/ExampleApp.js'`

**Comment by aether7** [comment]
It's already resolved with commit f8f42779d770ae5ac2e61998d6d9d2d6b6f1ae94
