### ISSUE TITLE
First component

### ISSUE THREAD

**Issue by Mentalchaos** [aether7/react-tutorial#12]
in section **My first component**  on the first ReactDOM.render()
the render is looking for an id called **example** but the actual name of the id is **app**
so you need to change

`ReactDOM.render(<ExampleApp />, document.getElementById('example'));`

to

`ReactDOM.render(<ExampleApp />, document.getElementById('app'));`

**Comment by aether7** [comment]
commit 3c0fbba
pr #17 
fixes #12
