### ISSUE TITLE
Atom instead of visual studio code (?)

### ISSUE THREAD

**Issue by Mentalchaos** [aether7/react-tutorial#14]
I think it's better to use **visual studio code** for this tutorial
Because **Atom** doesn't have a plugin to read **JSX** at the beginning
You need to manual-install it in order to read **JSX** files
(and your file "index" located in src/ has a **JSX** extension)

You can read JS files without problems but sometimes they bugged themselves for no reason in particular
(It happens to me twice when I was testing this tutorial using **Atom**)

**Comment by vcanales** [comment]
IMO, recommend both, or none. Choosing one makes it a bit impartial. Honestly, I'd go with mentioning that we use Atom and vscode at work, but that you can choose your own.
