### ISSUE TITLE
Implementation REMOVE_PRODUCT in Redux

### ISSUE THREAD

**Issue by worker-8** [aether7/react-tutorial#2]
In the manual Flux - Redux shows a wrong way of how to remove a product from the shopping cart, in the tutorial shows as next form:

```javascript
function shoppingCart(state = [], action){
  switch(action.type){
    case 'ADD_PRODUCT':
      return [...state, action.product];
    case 'REMOVE_PRODUCT':
      return {
        products: [
          ...state.slice(0, action.index),
          ...state.slice(action.index + 1)
        ]
      };
    default:
      return state;
  }
}
```
whereby when calling the action is finished spitting out an error in trying to re-render the section of the cart, originally the state is an array and in doing so the state becomes an object.

The solution to this problem is to realize the next:

```javascript
function shoppingCart(state = [], action){
  switch(action.type){
    case 'ADD_PRODUCT':
      return [...state, action.product];
    case 'REMOVE_PRODUCT':
      return [
          ...state.slice(0, action.index.idCart),
          ...state.slice(action.index.idCart + 1)
        ];
    default:
      return state;
  }
}
```

in this way the state will always be an array.

**Comment by aether7** [comment]
Already fixed in #9136291 commit ;)
