### ISSUE TITLE
url issue

### ISSUE THREAD

**Issue by Mentalchaos** [aether7/react-tutorial#5]
At the beginning of the tutorial on **'preparing the environment'** section we have a node.js link which is broken.
404 not found error
maybe you can get that error if you are using windows because links could change depending of your os
but I dont know if that is the problem

**Comment by aether7** [comment]
@Mentalchaos gonna check that ;)

**Comment by aether7** [comment]
@Mentalchaos it's already done, obviously just writing directly on master branch.
